/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Clientes;

import Model.Cliente;
import Model.DAO.ClienteDAO;
import java.awt.Graphics;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import view.Observaciones.Observaciones;

/**
 *
 * @author RavenTom
 */
public class Clientes extends javax.swing.JFrame {

    GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
    ClienteDAO clientdao = new ClienteDAO();
    DefaultTableModel modelo;
    FondoPanel fondo = new FondoPanel();
    
    /**
     * Creates new form crearpaciente
     */
    public Clientes() {
        this.setContentPane(fondo);
        this.setUndecorated(true);
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jPanel1.setOpaque(false);
        jPanel2.setOpaque(false);
        srch.setOpaque(false);
        edc.setOpaque(false);
        agc.setOpaque(false);
        Delete.setOpaque(false);
        rfrsh.setOpaque(false);
        ext.setOpaque(false);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowGainedFocus(WindowEvent e) {
                CleanTable();
                listclient();
            }
        });
        listclient();
    }
    
    public void listclient(){
        List<Cliente> Listcl = clientdao.ListCli();
        modelo = (DefaultTableModel) tablacli.getModel();
        Object[] obj = new Object[4];
        for(int i=0;i<Listcl.size();i++){
            obj[0]=Listcl.get(i).getDni();
            obj[1]=Listcl.get(i).getNcomp();
            obj[2]=Listcl.get(i).getTelefono();
            obj[3]=Listcl.get(i).getDireccion();
            modelo.addRow(obj);
        }
        tablacli.setModel(modelo);
    }
    
    public void searchclient(){
        List<Cliente> listcl = clientdao.SearchCli(Integer.parseInt(dnitxt.getText()));
        modelo = (DefaultTableModel) tablacli.getModel();
        Object[] obj = new Object[4];
        for(int i=0;i<listcl.size();i++){
            obj[0]=listcl.get(i).getDni();
            obj[1]=listcl.get(i).getNcomp();
            obj[2]=listcl.get(i).getTelefono();
            obj[3]=listcl.get(i).getDireccion();
            modelo.addRow(obj);
        }
        tablacli.setModel(modelo);
    }
    
    public void CleanTable(){
        for(int i =0;i<modelo.getRowCount();i++){
            modelo.removeRow(i);
            i = i-1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        agc = new javax.swing.JButton();
        edc = new javax.swing.JButton();
        ob = new javax.swing.JButton();
        ext = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tabcli = new javax.swing.JScrollPane();
        tablacli = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        dnitxt = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        rfrsh = new javax.swing.JButton();
        srch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        agc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        agc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CrearCliente.png"))); // NOI18N
        agc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agcActionPerformed(evt);
            }
        });

        edc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        edc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EditarCliente.png"))); // NOI18N
        edc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edcActionPerformed(evt);
            }
        });

        ob.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Observacion.png"))); // NOI18N
        ob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obActionPerformed(evt);
            }
        });

        ext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login.png"))); // NOI18N
        ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(ob, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(ext, javax.swing.GroupLayout.PREFERRED_SIZE, 65, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(agc)
                .addGap(37, 37, 37)
                .addComponent(edc)
                .addGap(43, 43, 43)
                .addComponent(ob)
                .addGap(261, 261, 261)
                .addComponent(ext, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tablacli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre Completo", "NRO Telefono", "Direccion"
            }
        ));
        tablacli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacliMouseClicked(evt);
            }
        });
        tabcli.setViewportView(tablacli);
        if (tablacli.getColumnModel().getColumnCount() > 0) {
            tablacli.getColumnModel().getColumn(0).setPreferredWidth(8);
            tablacli.getColumnModel().getColumn(1).setPreferredWidth(40);
            tablacli.getColumnModel().getColumn(2).setPreferredWidth(10);
            tablacli.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DNI");

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BorrarCliente.png"))); // NOI18N
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        rfrsh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        rfrsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfrshActionPerformed(evt);
            }
        });

        srch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabcli, javax.swing.GroupLayout.DEFAULT_SIZE, 1432, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(dnitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(srch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addComponent(rfrsh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dnitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rfrsh)
                                .addComponent(Delete))
                            .addComponent(srch, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(tabcli, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agcActionPerformed
       Crearcliente cp = new Crearcliente();
       cp.setVisible(true);
    }//GEN-LAST:event_agcActionPerformed

    private void tablacliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacliMouseClicked
        int fila = tablacli.rowAtPoint(evt.getPoint());
        dnitxt.setText(tablacli.getValueAt(fila, 0).toString());
    }//GEN-LAST:event_tablacliMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if(!"".equals(dnitxt.getText())){
           int pregunta = JOptionPane.showConfirmDialog(null, "¿Quieres eliminar el cliente?");
            if(pregunta == 0){
                int dni = Integer.parseInt(dnitxt.getText());
                clientdao.DelCLi(dni);
                CleanTable();
                listclient();
            } 
        }
        
    }//GEN-LAST:event_DeleteActionPerformed

    private void rfrshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfrshActionPerformed
        CleanTable();
        listclient();
    }//GEN-LAST:event_rfrshActionPerformed

    private void obActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obActionPerformed
        Observaciones obs = new Observaciones();
        obs.setVisible(true);
    }//GEN-LAST:event_obActionPerformed

    private void edcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edcActionPerformed
        Editarcliente ec = new Editarcliente();
        ec.setVisible(true);
    }//GEN-LAST:event_edcActionPerformed

    private void srchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchActionPerformed
        CleanTable();
        searchclient();
    }//GEN-LAST:event_srchActionPerformed

    private void extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extActionPerformed
        dispose();
    }//GEN-LAST:event_extActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton agc;
    private javax.swing.JTextField dnitxt;
    private javax.swing.JButton edc;
    private javax.swing.JButton ext;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton ob;
    private javax.swing.JButton rfrsh;
    private javax.swing.JButton srch;
    private javax.swing.JScrollPane tabcli;
    private javax.swing.JTable tablacli;
    // End of variables declaration//GEN-END:variables

class FondoPanel extends JPanel{
    private Image imagen;
    @Override
    public void paint(Graphics g){
        imagen = new ImageIcon(getClass().getResource("/img/Clientes.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }
}

}
